### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dbluxo** [resmoio/kubernetes-event-exporter#1]
Hi, thanks for the new fork, are you planning a release so the latest changes can be used?

**Comment by mustafaakin** [comment]
Sure thing, it's been a long holiday here, so I couldn't find enough time to setup a build pipeline. I want to make traceable builds. Should we release it under gchr or Docker hub?

**Comment by dbluxo** [comment]
Nice, both fine for me.

**Comment by mustafaakin** [comment]
Triggerred a release. Currently the multi-arch builds is very slow. An improvement is to build it with GOARCH=arm64 then prepare a Docker image, which should be faster. #6

**Comment by mustafaakin** [comment]
It's released! Enjoy:

https://github.com/resmoio/kubernetes-event-exporter/pkgs/container/kubernetes-event-exporter
