### ISSUE TITLE
Can not send http webhook

### ISSUE THREAD

**Issue by khanhnd48** [resmoio/kubernetes-event-exporter#109]
Here is my config:
logLevel: debug
logFormat: json
routes:
  - match:
    - receiver: "webhook"
receivers:		  
  - name: "webhook"
    webhook:
      endpoint: "https://eo4mhcl35g0gox5.m.pipedream.net" 
      headers:
        X-API-KEY: "123-456-OPSGENIE-789-ABC"
        User-Agent: "kube-event-exporter 1.0"
      streamName: "applicationMetric"
      layout:
        eventType: "kube-event"
        createdAt: "{{ .GetTimestampMs }}"
        details:
          message: "{{ .Message }}"
          reason: "{{ .Reason }}"
          tip: "{{ .Type }}"
          count: "{{ .Count }}"
          kind: "{{ .InvolvedObject.Kind }}"
          name: "{{ .InvolvedObject.Name }}"
          namespace: "{{ .Namespace }}"
          component: "{{ .Source.Component }}"
          host: "{{ .Source.Host }}"
          labels: "{{ toJson .InvolvedObject.Labels}}"

**Comment by mustafaakin** [comment]
Please provide the config as proper YML file so that we can reproduce.
