### ISSUE TITLE
Get events from a remote K8S cluster

### ISSUE THREAD

**Issue by bd3lage** [resmoio/kubernetes-event-exporter#117]
AFAIK it's not possible to get events from a remote K8S cluster using kubernetes-event-exporter.

Is this a feature that could be implemented ? Or do you think it's out of scope ?

**Comment by bd3lage** [comment]
Nevermind, I found it https://github.com/resmoio/kubernetes-event-exporter/blob/9e7f84ba16e77ac9a72c1bdee8df15aa65bc08c2/main.go#L22C1-L22C1

👍

**Comment by mustafaakin** [comment]
Yes, you can use a custom kubeconfig to connect another cluster. That's how I do my local development as well.
