### ISSUE TITLE
ETA for a stable release ?

### ISSUE THREAD

**Issue by lucj** [resmoio/kubernetes-event-exporter#13]
Following this comment, is there an ETA for a stable release so the code of this current repo can be integrated in Bitnami helm chart ? :) 

https://github.com/bitnami/charts/issues/11412#issuecomment-1216308934

**Comment by mustafaakin** [comment]
https://github.com/resmoio/kubernetes-event-exporter/actions/runs/3058972491
https://github.com/resmoio/kubernetes-event-exporter/releases/tag/v1.0

We've just released it.

https://github.com/resmoio/kubernetes-event-exporter/pkgs/container/kubernetes-event-exporter
