### ISSUE TITLE
RBAC `view` role is not engough sometimes

### ISSUE THREAD

**Issue by carlosjgp** [resmoio/kubernetes-event-exporter#14]
I'm getting this error
```
helmcharts.source.toolkit.fluxcd.io "karma-karma" is forbidden: User "system:serviceaccount:observability:event-exporter" cannot get resource "helmcharts" in API group "source.toolkit.fluxcd.io" in the namespace "flux-system""
```

Some applications with CRD would not decide for you what should be aggregated into the default Roles, in this case, FluxCD thinks that only FluxCD (cluster-admin) should be able to see these resources

**Comment by sidewinder12s** [comment]
Ya, generally you have to add any RBAC for CRDs it might try to export events about.
