### ISSUE TITLE
Only watch a single namespace

### ISSUE THREAD

**Issue by vanhoutenbos** [resmoio/kubernetes-event-exporter#140]
Hi!

We work on a multi-tenant cluster where we only have access to a single namespace, let says its called 'example-client-test'.
We only want to watch/list/get events from that single namespace.

At the moment we receive an error because the code is trying to list all events in the cluster scope:
`failed to list *v1.Event: events is forbidden: User "event-exporter-sa" cannot list resource "events" in API group "" at the cluster scope`

How can we fixate the exporter to only watch the namespace `example-client-test` and not try to list the others?

**Comment by Cheblan** [comment]
Hi!

According to this line of code (https://github.com/resmoio/kubernetes-event-exporter/blob/master/main.go#L92) you CAN pass **namespace** parameter inside config.yaml

UPD: Checked it myself, it is indeed working. Someone truly have to add this to documentation

**Comment by vanhoutenbos** [comment]
> Hi!
> 
> According to this line of code (https://github.com/resmoio/kubernetes-event-exporter/blob/master/main.go#L92) you CAN pass **namespace** parameter inside config.yaml
> 
> UPD: Checked it myself, it is indeed working. Someone truly have to add this to documentation

Thank you for the suggestions, I can't read go for some reason haha, I got it working and added it to the documentation as well!
