### ISSUE TITLE
feature: add `ownerReferences` to the exported events

### ISSUE THREAD

**Issue by ronaknnathani** [resmoio/kubernetes-event-exporter#143]
We have a use case where we need to emit events for objects and also capture the object's `ownerReferences`. I see that the event exporter already [enhances the events](https://github.com/resmoio/kubernetes-event-exporter/blob/master/pkg/kube/event.go#L41) with `labels` and `annotations`. The same struct can be used to also capture `ownerReferences`.

What do the maintainers think about this feature? We'd be happy to contribute this change.

**Comment by mustafaakin** [comment]
Of course, is already available in the call we make, why not?

**Comment by ronaknnathani** [comment]
Great! I can send a PR for this.

**Comment by ronaknnathani** [comment]
@mustafaakin created https://github.com/resmoio/kubernetes-event-exporter/pull/144. I have some more changes in the PR in addition to adding `ownerReferences`. Let me know what you think. Happy to iterate as needed.
