### ISSUE TITLE
ARM version images for kubernetes-event-exporter

### ISSUE THREAD

**Issue by Cloud-Shen** [resmoio/kubernetes-event-exporter#190]
Hello, our cluster is based on arm architecture,  are there any arm version images for kubernetes-event-exporter?

**Comment by LHozzan** [comment]
Hi there.
I [think yes](https://github.com/resmoio/kubernetes-event-exporter/pkgs/container/kubernetes-event-exporter).
Under "OS / Arch" I see `linux/amd64` and `linux/arm64`.
So, I expecting, that if you mean ARM64, this is the right image for you.
BR!

**Comment by Cloud-Shen** [comment]
Thanks for your reply, I wonder the tag of the arm64 version image so that I can just use docker pull to download it, since I can't obtain the tag list of this image.

**Comment by LHozzan** [comment]
We not using ARM architecture, but based on information [here](https://stackoverflow.com/a/69917870/8642014) I guessing something like this:
```bash
docker pull --platform linux/arm64 ghcr.io/resmoio/kubernetes-event-exporter:v1.7
```
After pulling you can check image SHA via inspect command and should be `sha256:5d91d04161637e0f01d5fd5aa8ce3a4a4b99952bf1cd9be5ddbe5ba204d049ba`.

All tags you find [here](https://github.com/resmoio/kubernetes-event-exporter/pkgs/container/kubernetes-event-exporter/versions?filters%5Bversion_type%5D=tagged).

Hope that helps.
