### ISSUE TITLE
Add ClusterName to Events

### ISSUE THREAD

**Issue by fpants** [resmoio/kubernetes-event-exporter#2]
When there are multiple clusters in an area it's essential to have the source clustername associated with each event. The event object exposed by Kubernetes provides a clustername, but it does not set it.

We've got some code here in testing that adds an optional "clusterName" to the config file, and if clusterName is set in the config file, then the clusterName is set in the event. This makes it easy to filter a stream of events by source cluster.

PR: #3

**Comment by xmcqueen** [comment]
we can close this one
