### ISSUE TITLE
Question: File Receiver Path

### ISSUE THREAD

**Issue by deltasparc** [resmoio/kubernetes-event-exporter#35]
Hi

In the path variable for the File Receiver, is /tmp/dump a directory or a file? If it's a directory, presumably the directory needs to exist and won't be automatically created. If it's a file, does that need to already exist? Also is this location on the k8s node where the exporter pod is running? 

Cheers

**Comment by mustafaakin** [comment]
It's a file and yes it does not create the folder on its own. It's a folder on pod. It's mostly for debugging cases or when you need to forward the file using filebit to somewhere else this project does not support.
