### ISSUE TITLE
Prometheus Metrics Coming Soon

### ISSUE THREAD

**Issue by xmcqueen** [resmoio/kubernetes-event-exporter#4]
I've got a PR coming that adds metrics to the exporter.  We need to know if this thing is up, down, or failing.  It's a pretty small PR and its working great in my testing.  

Metrics are essential.  If this thing is down in our clusters its a critical problem.  Other downstream systems rely on these events.  We watch the metrics and raise an alert if the metrics stop flowing.

**Comment by mustafaakin** [comment]
Yes, it'd be useful. It might be also useful to expose metrics by sinks.

**Comment by xmcqueen** [comment]
cool idea

**Comment by xmcqueen** [comment]
I've pushed it out everywhere. Its working great.  I'll get it in here soon.
