### ISSUE TITLE
Future of this project/fork

### ISSUE THREAD

**Issue by dbluxo** [resmoio/kubernetes-event-exporter#44]
My question is if [Resmo](https://github.com/resmoio) is behind this project and also wants to check it regularly? As my feeling is that there are currently already some PRs (including fixes for critical CVEs from me) that are unfortunately not reviewed and merged. Don't get me wrong, I understand that there is no entitlement here. I'm happy to contribute too, but there has to be someone there to supervise it, so I don't want to put my efforts on a "dead" project.

cc @mustafaakin

**Comment by oguzhancelikarslan** [comment]
@mustafaakin thanks all of you.

**Comment by dbluxo** [comment]
> Hello @dbluxo, you are absolutely right, sorry for the late responses, we were in re:Invent last week and was busy with our product launch in November. We'll take care of the outstanding PRs now and the future ones in a more timely manner.

Unfortunately, the situation has not improved. Could you imagine looking for other maintainers with the appropriate rights so that it is possible to support the project and give the kubernetes-event-exporter a better future?

**Comment by mustafaakin** [comment]
You are right @dbluxo we've neglected this repository a bit. I'm looking into PRs now and will put up a banner to indicate a search for maintainers.
