### ISSUE TITLE
Truncate messages via char limitation. 

### ISSUE THREAD

**Issue by assafmanzur** [resmoio/kubernetes-event-exporter#56]
Hi, team our Splunk agent has a limitation of 15k characters anything more than that will be truncated. As for those msgs are do not getting the proper formatting in Splunk 

We are using the stdout configuration, can we limit the msg chars in some way?

**Comment by mustafaakin** [comment]
Trimming would invalidate the messages. You can have a custom layout to reduce the number of fields you are interested.
