### ISSUE TITLE
Speed up multi-arch builds

### ISSUE THREAD

**Issue by mustafaakin** [resmoio/kubernetes-event-exporter#6]
arm64 builds are very slow. Takes around 30 minutes due to using docker buildx creating an emulated arm64 image. We can modify the build to use `GOARCH=arm64` and just copy the file to a Docker image which should be much faster - compiling lots of huge dependencies in emulated VM is slow.

**Comment by grzesuav** [comment]
actually I got pretty good result with using `goreleaser` to do multi arch build and wrap them - https://github.com/grzesuav/metacontroller/releases/tag/v1.3.0 see https://github.com/grzesuav/metacontroller/runs/7771499943?check_suite_focus=true `Release` step - it takes 8 minutes to do that end to end
