### ISSUE TITLE
Index Template Management For Elasticsearch/Opensearch

### ISSUE THREAD

**Issue by allahshukur-ahmadzada** [resmoio/kubernetes-event-exporter#65]
I see receivers like opensearch and elasticsearch does not add custom templates, is there any plans to add it? because we do migration from metricbeat to your project  we compare both and I see metricbeat creates a large custom index template and additionally is supports user to configure shards and so

**Comment by mustafaakin** [comment]
Unfortunately there is not. As you can configure the layout as you wish, it does not make sense to provide a fixed template.
