### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by gsmith-sas** [resmoio/kubernetes-event-exporter#67]
I notice there haven't been any new commits to this project since December.  This is concerning, especially since this project was forked after work ceased on the original opsgenie project.  Can the maintainers confirm this project is still active?  Is Resmo still supportive of this effort?  Is there a specific timeline for when a new release will be available?

I am NOT complaining, thank you for your efforts so far.  I am just trying to understand the status of things so we can make good choices about the projects we use.

**Comment by mustafaakin** [comment]
Hi @gsmith-sas , thanks for bringing it to our attention. It's still active, we %100 support it, but there have not been major PRs, and the project is fairly stable. Is there a specific PR you need to be merged and released, we can speed up the merging of them.

**Comment by gsmith-sas** [comment]
Thanks for the quick reply @mustafaakin and for the good news!  No, there wasn't a specific PR I was concerned about.  I did see some issues that mentioned that the documentation didn't match the code in the repo so I thought a new release might be coming out.  I'm looking for a replacement for Event Router and didn't want to go too far with this project if it has met a similar fate.  Thanks again.
