### ISSUE TITLE
Set up versioning

### ISSUE THREAD

**Issue by grzesuav** [resmoio/kubernetes-event-exporter#7]
To easy distinguish what comes in given release and to distinguish images via tag, I propose to enforce semantic versioning for repository, sth like https://github.com/metacontroller/metacontroller/releases

**Comment by grzesuav** [comment]
@mustafakin I can help with that

**Comment by mustafaakin** [comment]
We are using Github Releases which are also based on Git tags right now + and wired to Actions. https://github.com/resmoio/kubernetes-event-exporter/releases/tag/v1.0-alpha

Do you have something else in mind?

**Comment by grzesuav** [comment]
ah, didn't seen that, just tags were exposed on first sight. Yes, I had something similar in mind, maybe with docker  images listed like https://github.com/grzesuav/metacontroller/releases/tag/v1.3.0

**Comment by grzesuav** [comment]
@mustafaakin what your views on sth like https://github.com/metacontroller/metacontroller/releases/tag/v4.3.7 - 
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/9568421/185929333-7d05710e-f27a-4eb9-b104-be0c8992c8e3.png">

so :
* semantic commits
* semantic versioning
* automatic release generation, with changelog
* `goreleaser` for binary / docker builds
?

Currently looking at https://github.com/resmoio/kubernetes-event-exporter/tree/master/.github/workflows I do not see how the releases are made, however I think improvements are possible
