### ISSUE TITLE
Problem with collecting logs with filebeat

### ISSUE THREAD

**Issue by ksponomarev** [resmoio/kubernetes-event-exporter#70]
Hello. 
I'm using events exporter with stdout receiver. Filebeat collects data from stdout but gets the error like:
```
parsing input as JSON: invalid character 'I' looking for beginning of value
```
Maybe u have seen this error before? How can I fix it?

**Comment by mustafaakin** [comment]
Stdout is used for regular logs as well, ensure it's configured as JSON in the config file as well. I'm not sure which log are you referring to.
