### ISSUE TITLE
loglevel

### ISSUE THREAD

**Issue by hivl** [resmoio/kubernetes-event-exporter#74]
Hi,
what does loglevel in the configmap exactly do? is it a loglevel for the container itself or does it affect the events which will be exported?
Thank you

**Comment by Evedel** [comment]
Hey @hivl,

That is only for internal app logs. It should be possible to control the event's log level with
```
  type: "Normal"
```
https://github.com/resmoio/kubernetes-event-exporter/blob/master/config.example.yaml#L17

**Comment by hivl** [comment]
thank you @Evedel
