### ISSUE TITLE
Helm chart image tag should be specified

### ISSUE THREAD

**Issue by thomaschaaf** [resmoio/kubernetes-event-exporter#77]
Currently the helm chart is pointing to "latest": https://github.com/resmoio/kubernetes-event-exporter/blob/master/charts/kubernetes-event-exporter/values.yaml#L11

Setting the tag to null causes the chart version to be used which does not exist in the repository.

```yaml
image:
  tag: null
```

Other projects specify the version: https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L102-L104 that way `latest` isn't used.

**Comment by mustafaakin** [comment]
We've discontinued Helm support in this repository. Please use Bitnami chart.
