### ISSUE TITLE
Release strategy/naming convention

### ISSUE THREAD

**Issue by gsmith-sas** [resmoio/kubernetes-event-exporter#79]
@mustafaakin Can you clarify this project's release strategy?  I see there was a v1.0 release followed by a v1.1 release last December.  But then there was a release called "kubernetes-event-exporter-0.1.0" made available in March.  Does that release represent the "next" release after v1.1?  Or, does it represent a branch for some other purposes?  Should we expect to see additional releases using one or both naming/numbering conventions moving forward?

I want to make sure I understand how things are being handled so I can be sure I'm using the "right" version of things.  Thanks!

**Comment by grzesuav** [comment]
plus one, so the 0.1.0 is the newest version ? I do not see any release notes

**Comment by grzesuav** [comment]
As I wrote in https://github.com/resmoio/kubernetes-event-exporter/issues/7 I can help with setting up semantic versioning etc

**Comment by grzesuav** [comment]
Also, I do not see docker images being pushed for the lates `0.1.0` tag

**Comment by hkfgo** [comment]
Hey just following up on this, it looks like the image is still not released?

**Comment by dgomezleon** [comment]
Hello,
We also wanted to know more about the versioning convention for the project. In Bitnami, we have been offering it as 1.1.0 (we use semver versioning) until the previous version. Now we have a problem since the newly detected version is lower than the previous one, so it will not be released unless we patch it somehow.

**Comment by ChenglongLiu** [comment]
Seems this PR #54  introduced an automation release workflow for the repo.

**Comment by mustafaakin** [comment]
Hello, sorry for late reply. We are manually increasing the versions from now on. The latest release is 1.2 as of now. Unless it's a very major rewrite, it'll go as 1.3 to 1.99999 (hopefully not that many releases)
