### ISSUE TITLE
Do not logging the events or username

### ISSUE THREAD

**Issue by antikilahdjs** [resmoio/kubernetes-event-exporter#83]
Hello everyone.

I would like to know if possible logging that all the users done without use the kube-apiserver to logging audit. I tried configured the event-export but I cannot see if an user scale down some pods , when do something in k8s and so on. 

I am new using this exporter and I need a guide about it pls. Tks

**Comment by grzesuav** [comment]
User information is not in the kubernetes events, so it cannot be exported

**Comment by antikilahdjs** [comment]
Thank you so much @grzesuav
